version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: my_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_custom_service
    depends_on:
      - postgres
      - mongo
      - redis
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      MONGO_URI: mongodb://root:password@mongo:27017
      REDIS_HOST: redis
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  mongo_data: